using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Reflection;
using System.Text;
using P02.ORMExplore.Framework.SqlMapping;
using P02.ORMExplore.Model;

namespace P02.ORMExplore.DAL
{
    public class MySqlBuilder<T> where T : BaseModel
    {
        public static string FindSql = "";
        public static string FindAllSql = "";
        public static string InsertSql = "";
        public static string DeleteSql = "";
        public static string ModifySql = "";

        public static string tableName = "";
        //should be public, for add method
        public static PropertyInfo[] propList;
        public static PropertyInfo[] propListAllPub;
        //that's how to cache the fixed sql .  Generic method cache. 
        //use static construction method, which only run one time.(So cache reduce the time of running this method)
        //for different T, the compiler will generate different class.
        //faster than dictionary(100), because dic store in hash table, search in memory,
        //Generic class are  already compiled, so search in Cache.
        //note: the properties in sql should be same to the properties you create obj(eg. for each get more prop?!)
        static MySqlBuilder()
        {
            Type type = typeof(T);
            propList = type.GetProperties(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Public);
            propListAllPub = type.GetProperties(BindingFlags.Instance | BindingFlags.Public);
            T t = Activator.CreateInstance<T>();
            tableName = t.ClassMapping();

            InsertSql = InsertSqlBuilder<T>();
            FindAllSql = FindAllSqlBuilder<T>();
            FindSql = FindSqlBuilder<T>();
            DeleteSql = DeleteSqlBuilder<T>();
            ModifySql = ModifySqlBuilder<T>();
        }

        public static X CreateObjectFromSqlDataReader<X>(SqlDataReader reader) where X : BaseModel
        {
            //Use X because the generic type in static method can be different from class generic type
            // can also use T but there will be a warning. 
            object obj = Activator.CreateInstance(typeof(X));
            foreach (var prop in propListAllPub)
            {
                // notice the null from database //prop.GetColumnName() is to get/check database name in attribute
                //since sql uses alias, so still use prop.Name. 
                prop.SetValue(obj, reader[prop.Name] is DBNull ? null : reader[prop.Name]);
            }
            return (X)obj;
        }
        private static String ModifySqlBuilder<X>() where X : BaseModel
        {
            //Type type = typeof(X);//not get table name through type
            //don't set id, id just in where clause, so use proList here, for building params, need to have id.
            String Sql = "Update a " +
                         $"Set {String.Join(" , ", propList.Select(p => $" [{p.GetColumnName()}] = @{p.GetColumnName()} ")) } " +
                         //$"From [{type.Name}] a " +
                         $"From [{tableName}] a " +
                         $"Where id = @id ";
            return Sql;
        }
        private static string DeleteSqlBuilder<X>() where X : BaseModel
        {
            //Type type = typeof(T);
            String Sql = $"Delete From [{tableName}] where ID = @id";
            return Sql;
        }
        private static string FindSqlBuilder<X>() where X : BaseModel
        {
            //Type type = typeof(T);
            //id is assigned by DAL
            string columnString = $"{string.Join(" , ", propListAllPub.Select(p => $"[{p.GetColumnName()}] as [{p.Name}]"))} ";
            string Sql = $"SELECT {columnString}" +
                         $"FROM [{tableName}] " +
                         "WHERE ID = @id";
            return Sql;
        }
        private static string FindAllSqlBuilder<X>() where X : BaseModel
        {
            //Type type = typeof(T);
            // must use as p.name, because you need to create object based on the column name from sqlreader, 
            String columnString = string.Join(" , ", propListAllPub.Select(p => $"[{p.GetColumnName()}] as [{p.Name}]"));
            String sql = $"Select {columnString} from {tableName} ";
            return sql;
        }

        private static string InsertSqlBuilder<X>() where X : BaseModel
        {
            // avoid sql injection, so use parameterized query
            Type type = typeof(X);
            var test = type.GetProperties();
            var tlinq = type.GetProperties().Select(p => p.Name);
            //should not have inherted members. id is generated by database.
            String columnString = string.Join(",", propList.Select(p => $"[{p.GetColumnName()}]"));

            String valueColumn = String.Join(",", propList.Select(p => $"@{p.GetColumnName()}")); //not get value, prepare @value as parameter name
            String sql =
                $"INSERT INTO [{tableName}]  ({columnString}) values ({valueColumn})";
            return sql;
        }
    }
}
